# Generated by Django 2.0.4 on 2018-05-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('is_official', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('owner', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='date_createsd',
            new_name='date_created',
        ),
    ]
